### ISSUE TITLE
Installation location

### ISSUE THREAD

**Issue by smac89** [scop/bash-completion#105]
Running on Ubuntu 16.04, the expected installation paths are different. For example

- `bash_completions` was installed to `/usr/local/share/bash-completion/bash_completion` rather than `/usr/share/bash-completion/bash_completion`
- Had to manually copy `bash_completions.sh` to `etc/profile.d/`

**Comment by scop** [comment]
bash-completion uses the usual autotools default installation locations, which quite likely means everything goes to `/usr/local` unless you tell `configure` otherwise, and that's expected. Something like `./configure --prefix=/usr --sysconfdir=/etc` would possibly achieve what I gather you expected the install locations to be.
