### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [scop/bash-completion#1088]
## Describe the feature/solution

It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by akinomyoga** [comment]
- [Issue search results](https://github.com/search?q=%22Move+code+to+GitLab+or+Codeberg%22&amp;type=issues)
- [Discussion search results](https://github.com/search?q=%22Move+code+to+GitLab+or+Codeberg%22&amp;type=discussions)

People are already replying with reasons for not moving to another host. Also, https://github.com/orgs/FossifyOrg/discussions/37 seems to contain interesting arguments.

BTW, many issues with the same content shouldn't be opened (unless you can properly make 40 discussions in parallel at the same time, summarize all the discussions, and share the summary with all the issues continuously). However, I don't see any replies from you on those issues. This would be considered spamming. This seems already pointed out by https://github.com/beemdevelopment/Aegis/issues/1254#issuecomment-1874666297, and then you have hidden your activity without any replies. This is generally considered not an accepted attitude.

I guess a proper way should be, for example, to open an issue in one specific repository, probably one of yours, and mention and gather the developers of OSS in one thread. If you are still willing, it's not too late to close all those issues with apologies, create a central one, and gather the developers in that place. Also, there should have been already similar discussions in many places on the web, so it would be desired to summarize them for a person to raise the discussion.

**Comment by akinomyoga** [comment]
Thank you for taking the time to reply.

> There is no right or wrong answer, and I expect most projects will stick with their current code host, but not all!

Then, it would have been better to state that in a fair way in the first comment. Even with that, I have to say that the promotion of an idea in this way wouldn't work *socially* even if the statement were correct. In particular, when you try to talk to the people who weren't interested in it. Handling issues would require resources, i.e., maintainers supposedly need to take time to properly think about many possibilities related to the issue, to collect the opinions from the users, and to make decisions properly. Considering that you knew that the suggestion wouldn't be accepted by most projects, opening many GitHub Issues for that topic everywhere would steal large resources from people for discussions less likely to cause an actual action. Next time, if any, you'll be able to do it better.

To discuss the main topic, I understand your concern to some extent, but your opinion appears to be a bit too naive to me. The statement appears to fit in the typical naive picture of Microsoft vs the others, but the reality is not that simple. We should remember the fact that we need money to sustain a large-scale service. No company can sustain the service without pursuing profit. Before Microsoft decided to support GitHub, this service was unsustainable and about to shut down. Currently, GitLab and Codeberg might be able to operate their service, but if everyone moves from GitHub to those, I doubt they would be able to offer the same quality of service without being owned by a large company. One might think Microsoft is an exceptionally evil company, but that's not the case. All the companies need to decide to make money to sustain the service instead of committing double suicide with the service. Or at least, it is impossible to convince the stockholders to continue to offer unlimited free lunches forever. Just Microsoft gathers attention because of its size. Your concern is a real one for sure, but it is *unclear* whether moving to other services would essentially change this structural issue. Also, only the fact that we can move to other services anytime would work as a deterrent. It's just my thought, but *I feel* the action to move to another host against Microsoft is allergic and immature. There is no reason to take time and effort on the migration for an obscure fear about Microsoft, at least for now. Reality is complicated anyway.

**Comment by scop** [comment]
Thanks for the suggestion and discussion. However, I don't think moving the project is worth the trouble at this time.

**Comment by akinomyoga** [comment]
@julianfairfax Thank you for raising a discussion anyway, though this time we are not interested in the move.
