### ISSUE TITLE
Nit

### ISSUE THREAD

**Issue by Sinyo73** [scop/bash-completion#1165]
## To reproduce

1. cd to '...'
2. Type '....'
3. See problem

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version:
- [ ] bash version, `echo "$BASH_VERSION"`:
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`:

**Comment by scop** [comment]
I'm afraid I don't see the problem. Could you elaborate and include the debug trace?

**Comment by akinomyoga** [comment]
The cover message is identical to the template. Maybe the issue is opened mistakenly. Or is it a request for the completion setting for a tool Nit? I searched for Nit, but I only find [`apotonick/nit`](https://github.com/apotonick/nit) and [`withnic/nit`](https://github.com/withnic/nit), which do not seem to be used by many people.
