### ISSUE TITLE
Enable .java Filename Completion for java Command

### ISSUE THREAD

**Issue by jiri-pejchal** [scop/bash-completion#1196]
## Description
Enhance the bash completion scripts for the `java` command to complete filenames with the `.java` extension.

This enhancement is necessary to support:
- JEP 330: Launch Single-File Source-Code Programs 
- JEP 458: Launch Multi-File Source-Code Programs 

which allows the java launcher to run a program supplied as a single file of Java source code:
```
java HelloWorld.java
```

**Comment by jiri-pejchal** [comment]
The completion could be further improved by having the completion suggest only `.java` files that contain the method `main`, which serves as the entry point for program execution. 

Files without the `main` method cannot be launched with the `java` command.

Perhaps complete on `.java` files with content matching `void main`.

Following the implementation of [JEP 477](https://openjdk.org/jeps/477), the `main` method could appear in any of the following forms:

```java
static void main(String[] args) {
  println("Hello, World!");
 }
```
```java
static void main() {
  println("Hello, World!");
}
```
```java
void main(String[] args) {
  println("Hello, World!");
}
```
```java
void main() {
  println("Hello, World!");
}
```

I don't know if it is feasible or how it could be implemented.

**Comment by akinomyoga** [comment]
> I don't know if it is feasible or how it could be implemented.

To perform that robustly, we would need a compiler or, at least, a Java parser. If the `java` command (or any associated tool) itself can list the files that contain the proper `main` function, we can use that.

One might think it could be possible to detect the main function by matching a fixed string, but it's not robust. That can mistakenly hit an unrelated string in a code comment, or it might miss the actual main function by a tiny style difference. I'm not sure if we should add the completions that can produce wrong results *randomly* at a small probability, because the users would learn to believe the list generated by `bash-completion`, which would tell a lie at a small probability and cause a mistake. [Note: Of course, it is not *random* in a strict sense, but it's non-trivial to explain to the users in what situations the completion fails or succeeds.]. That said, such a native implementation would probably work in most cases. This would be a matter of the preferences of the maintainer.
