### ISSUE TITLE
kmod upstream integration

### ISSUE THREAD

**Issue by evelikov** [scop/bash-completion#1246]
## Describe the feature/solution

Hello team, I'm considering pulling the bash completion files (as do zsh and fish fwiw) in the upstream kmod project. At a glance, a few questions come up:
 - is the license `SPDX-License-Identifier: GPL-2.0-or-later` or `SPDX-License-Identifier: GPL-2.0-only`?
 - would the team be comfortable with relicensing under `LGPL-2.1-or-later` - like the existing completion in kmod?
 - are there any copyright holders which I could/should add in the files themselves?
 - how do we handle the conflicting filenames, if distros ship the same file(s) from both projects?
 - can I still use the various helpers (_comp_compgen_inserted_kernel_{modules,versions} _comp_compgen_filedir etc) and if so, for how long?

Thanks o/

**Comment by akinomyoga** [comment]
> ## Describe the feature/solution
> Hello team, I'm considering pulling the bash completion files

Which files are you specifically talking about? We do not seem to ship any completions for `kmod` ([search](https://github.com/search?q=repo%3Ascop%2Fbash-completion%20%2F%5Cbkmod%5Cb%2F&type=code)). Do you intend to include the core components of `bash-completion` as a part of the `kmod` project?

> (as do zsh and fish fwiw) in the upstream kmod project.

The actual situation seems the opposite. I've checked how zsh/fish completions are shipped with the `kmod` project, but zsh/fish completions do not seem to be included in the kmod project. Instead, there's already a bash-completion file for Bash [here](https://github.com/kmod-project/kmod/tree/master/shell-completion/bash).

> At a glance, a few questions come up:
> 
> * is the license `SPDX-License-Identifier: GPL-2.0-or-later` or `SPDX-License-Identifier: GPL-2.0-only`?

Please check the copyright notice. It's `GPL-2.0-or-later`.

https://github.com/scop/bash-completion/blob/e8dc253ddda79f83532551e45deeeab0c3afc5f4/bash_completion#L3-L11

> * would the team be comfortable with relicensing under `LGPL-2.1-or-later` - like the existing completion in kmod?

It is practically difficult. I can relicense the part I contributed, and we can ask the same for the parts that the other current maintainers have contributed. However, many parts are contributed by many people with whom we don't have a way to contact now. We haven't been requesting any copyright assignment, the disclaimer of the copyright, or the right to relicense the codes when we accept contributions. Thus, the copyright holder of each piece of code is legally still the original author of that part, and I think we don't have the right to relicense those parts. These parts are tightly integrated into the `bash-completion` project, so if we are to relicense the entire bash-completion project, we'll need to scan all the change history of the codebase and remove the parts contributed by the people who we currently do not have a way to contact with. Then, we need to re-implement all the core parts that were removed. That seems too much just to relicense the codes for the `kmod` project.

> * are there any copyright holders which I could/should add in the files themselves?

If you want to include copyright notices in each file ported from `bash-completion`, you can basically copy this part:

```bash
 #   Copyright © 2006-2008, Ian Macdonald <ian@caliban.org> 
 #             © 2009-2020, Bash Completion Maintainers 
```

Also, you need to retain the existing copyright notices in each completion file if any. For example, `completions/sitecopy` contains the following copyright notices (which you cannot remove when you copy the file into the `kmod` project):

https://github.com/scop/bash-completion/blob/e8dc253ddda79f83532551e45deeeab0c3afc5f4/completions/sitecopy#L2-L3

> * how do we handle the conflicting filenames, if distros ship the same file(s) from both projects?

If the upstream project like `kmod` ships their completion file `kmod`, `bash-completion` will not ship the `kmod` completion. If `bash-completion` were shipping the `kmod` completion, we would be supposed to rename the file `kmod` to `_kmod` in `bash-completion`. Then our dynamic loader will first look `kmod` that is supposed to be provided by the upstream `kmod` project and use `_kmod` as a fallback when `kmod` is not found.

If the `kmod` project would be going to manage an entire copy of `bash-completion` and installs it in the system, it should be installed in a separate directory, such as `/usr/share/kmod/bash-completion`. In addition, if you consider the case that both copies of `bash-completion` are loaded in users' Bash sessions, you'd probably need to rename all the APIs (e.g. by prefixing `_kmod` to the shell function and variable names) to avoid conflicts between different versions.

> * can I still use the various helpers (_comp_compgen_inserted_kernel_{modules,versions} _comp_compgen_filedir etc) and if so, for how long?

These new names (`_comp_compgen_inserted_kernel_{modules,versions}`, etc.) are supposed to become the public API for the next major version of bash-completion 3 (there is no consensus among the maintainers just because we haven't discussed this explicitly, but it should be so practically). These are added in 2.12. Since these are not supported by all the packages of `bash-completion` in the market (there are still distributions with `bash-completion <= 2.11`), if you are going to rely on them, you'll have to still use the bash-completion 2 API such as `_installed_modules`. The bash-completion 2 APIs are supposed to be maintained for about ten years. I guess the bash-completion 3 APIs are supposed to be maintained for 20 years as far as this project continues.

> 
> Thanks o/

**Comment by akinomyoga** [comment]
> Of the above list, this repo has `insmod`, `rmmod` `modprobe` and `modinfo`.

Thank you for the clarification.

> Neither of which has particular copyright references. Is it OK to include a header as below:
> 
> ```
> This file is based on the completion from https://github.com/scop/bash-completion/, git tag 2.14.0.
> See the repository for the original authors and additional copyright holders.  
> 
> Copyright © 2006-2008, Ian Macdonald <ian@caliban.org> 
>               © 2009-2020, Bash Completion Maintainers 
> ```
> 
> What can I do for the above 4 bash-completions to be properly prefixed?

If the license of the entire project is different from (less restrictive than) "GPL-2.0-or-later", could you also state that these specific completion files are distributed under "GPL-2.0-or-later" (in each file or in some documentation that summarizes the copyrights of the project components)?

Technically, in addition to the people mentioned above, there should be contributors who provided the specific completions. To find out the original copyright holders, we need to check the change history of the codebase of `bash-completion`. However, it should be fine as far as we mention that the copyright holders would be recorded in the git history of `bash-completion` (since the copyright notices were not explicit in most cases in `bash-completion` either).

> Looking at zsh and fish, they use different folders for project-provided completions vs shell-provided ones. Would it make sense for bash-completions to adopt a similar approach? As even with the rename, there will be an overlap where distros have conflicting files.

That is related to the second and third questions in [FAQ in README](https://github.com/scop/bash-completion?tab=readme-ov-file#faq). Although we don't provide a way to overwrite the conflicting completion settings dynamically, one can still overwrite them using the eagerly loaded completion settings put in `/etc/bash_completion.d`. Or a distribution can set the default `BASH_COMPLETION_USER_DIR` so that `bash-completion` look into two different locations pre-defined by the distributions (one for the original completions shipped with `bash-completion` and another for the overwriting completions).

However, I see it is cleaner to set it up by the upstream `bash-completion` project officially.

**Comment by evelikov** [comment]
Thanks everyone - the MR has landed, closing issue.
