### ISSUE TITLE
tests: Please increase the default expect timeout

### ISSUE THREAD

**Issue by mgorny** [scop/bash-completion#133]
When I run `make check` initially, I have multiple (10-15) test failures due to timeouts. This seems to be partially related to cold cache but some tests just take very long on my PC. Since many people are going to run tests with cold cache (it's a normal case after all), and on systems that are not idle, the default timeout is much too small for them.

Could you please consider increasing the timeout by default? I have confirmed that with the timeout of 60 seconds all tests work fine for me. However, for real use cases even a larger value could be reasonable. After all, I don't think that we need to account for bash-completions hanging indefinitely.

**Comment by scop** [comment]
I'd rather not increase the timeout. Any completion taking that long should be checked and seen if something could be done about making it faster, no matter the cache state.

ISTR failures like these can also be because of insufficient buffer size for expect; that's something we can raise if necessary, but there have been at least until now ways to work around it by limiting the number of suggestions offered by the test case completions.

Your screen case should be taken care of now with 1c5d13ee8c60cc2ef22751d9e876296be731d749, info is not yet. Please file new issues for the remaining slow/unresolved ones and let's have a look at them case by case.

**Comment by mgorny** [comment]
Thanks for the explanation. I've filed the respective bugs for all cases of timeout and buffer size problems.
