### ISSUE TITLE
scp completion fails if "ssh" is overridden with a shell function

### ISSUE THREAD

**Issue by aabdnn** [scop/bash-completion#149]
Hi folks. In my .bash_profile, I have a shell function called "ssh". This shell function calls the real ssh (/usr/bin/ssh) with a custom command that attaches to tmux sessions on remote hosts. This all works fine for ssh, but it has broken scp completion, because the scp completion calls "ssh", and this is calling my function instead of the real ssh.

Is it possible for you to modify the 3 calls to ssh in the scp completion function, and prepend them with "command", like this?

```
     # default to home dir of specified user on remote host
     if [ -z "$path" ]; then
-        path=$(ssh -o 'Batchmode yes' $userhost pwd 2>/dev/null)
+        path=$(command ssh -o 'Batchmode yes' $userhost pwd 2>/dev/null)
     fi
 
     local files
     if [ "$1" = -d ] ; then
         # escape problematic characters; remove non-dirs
-        files=$( ssh -o 'Batchmode yes' $userhost \
+        files=$( command ssh -o 'Batchmode yes' $userhost \
             command ls -aF1d "$path*" 2>/dev/null | \
             sed -e 's/'$_scp_path_esc'/\\\\\\&/g' -e '/[^\/]$/d' )
     else
         # escape problematic characters; remove executables, aliases, pipes
         # and sockets; add space at end of file names
-        files=$( ssh -o 'Batchmode yes' $userhost \
+        files=$( command ssh -o 'Batchmode yes' $userhost \
             command ls -aF1d "$path*" 2>/dev/null | \
             sed -e 's/'$_scp_path_esc'/\\\\\\&/g' -e 's/[*@|=]$//g' \
             -e 's/[^\/]$/& /g' )
```

This ensures that the real ssh is always called and scp completion works again as it should.

**Comment by scop** [comment]
I guess `_ssh_query` can be similarly affected. But I'm not sure I'm a big fan of this change, why single out ssh? Wouldn't any command we invoke be susceptible for this kind of breakage in presence of functions or aliases misbehaving? To address this we should prefix pretty much everything with `command`, and I'm not  convinced we should go there.

Instead, I tend to think that it would be better to fix your function so that it doesn't break the usual basic behavior of ssh. If it cannot be done in generic way, perhaps check if some of `COMP_*` env variables are set, indicating that a bash completion is in progress, and modify the behavior accordingly.

**Comment by aabdnn** [comment]
Hi @scop. I agree that it's a bit silly to prefix everything with "command". After your comment, I went and looked at my function again, and realised that I could improve it in a way that doesn't break scp completion. Now scp completion works, without having to prefix "command" to ssh calls. Apologies for opening this bug report and wasting your time.

**Comment by scop** [comment]
No problem.
