### ISSUE TITLE
pylint and pydoc autocompletion does not work if only python3 is installed

### ISSUE THREAD

**Issue by piecot** [scop/bash-completion#166]
Hi,
if only python3 is installed (no pythonn executable, but only python3), the auto-completion for pylint  and pydoc fails, providing the following error when TAB is pressed:

> bash: python: command not found

The pylint & pydoc scripts could be enhanced in order to detect the version of python installed.

**Comment by scop** [comment]
Not a fix, but FWIW pydoc (and now, since 6e2a972b87d0e1571bf1bc635071831c0742ca37 pylint too) invokes python3 if the pydoc or pylint command name contains 3, i.e. if they're invoked e.g. as pydoc3 or pylint-3.

I can't think of a clean way to properly fix this -- it's not that clean to retry with python3 if the python try fails (or vice versa if we first tried with python3. or with python2 instead of python...).

**Comment by piecot** [comment]
Ok, I used an old version of the package. 
I agree with your point of view: if pydoc3 or pylint3 is being used, it can be safely assumed that python3 is installed. 

Thanks!
