### ISSUE TITLE
Other file types for web browsers

### ISSUE THREAD

**Issue by arschficken** [scop/bash-completion#230]
Web browsers are designed to display diverse file types. For a programmer, they are particularly useful for viewing images and a plethora of text files (especially in encodings that confuse terminals and text editors), which may have arbitrary extensions. Users also play videos and sound files through them. Mozilla browsers need to expand [XPI files](https://en.wikipedia.org/wiki/XPInstall) to install add-ons.

Other programs capable of handling many file types, such as vlc, don't have any autocompletion entries, so they always expand the file the user is after.

But the current completion rules for firefox, chromium-browser, etc. seem to cover only *HTML and PDF files, thus preventing the above use cases.

Perhaps usability would be improved by similarly _removing_ the "firefox ..." line from bash_completion?

**Comment by bewuethr** [comment]
Perhaps using a name that is a tad more professional would help people to take you seriously?

**Comment by scop** [comment]
I'm open to associating more file extensions with browsers. Other than that, see the first FAQ item. https://github.com/scop/bash-completion/blob/master/README.md#faq

We don't have a completion for vlc, so that point isn't applicable here. We do however have one for mplayer, xine etc which are similar, and we do have a long list of file extensions applied to them.

**Comment by arschficken** [comment]
Thanks! Meta+/ seems to only work in VTs (presumably due to the window manager trapping Meta), but Esc / indeed expands arbitrary filenames, and is a good workaround for the general case. This is a satisfactory solution for opening random files in Firefox and other programs.
