### ISSUE TITLE
bash-completion fails silently when bash version is too old

### ISSUE THREAD

**Issue by mojotx** [scop/bash-completion#259]
When a user attempts to use bash-completion with a version of bash that is too old (version < 4.1), the script fails silently with no indication to the user that anything went wrong. 

Apple macOS still ships with bash 3.2.57, because that was the last version that was released with GPL v2. It is possible to install a newer version of bash, but first the user needs to know that's the issue.

**Comment by mojoTX** [comment]
Installing bash-completion with the Homebrew package manager isn't an issue, because the package manager knows about the dependency on bash > 4.1. In other words, if you issue the command `brew install bash-completion`, it will also require you to have a newer version of bash installed. My situation is an edge case, since most people use a package manager. 

In my case, this is a Mac used in a restricted and highly regulated Fortune 100 corporate environment, where we do not have access to the Homebrew package manager, and every third-party application requires corporate and legal review and approval. The use of Macs within this organization is fairly new, so it's still a work-in-progress. 

I sought (and received) permission to evaluate bash-completion for our environment, without being aware of the bash 4.1+ requirement. I've used bash-completion for years, but it's always been installed with a package manager. That's why I wasn't aware of the version issue.

You wrote, 
>I'd say that's the thing people who don't want to read install instructions/comments should be using

However, the bash version requirement is not clearly mentioned in the [README.md](https://github.com/scop/bash-completion/blob/master/README.md) file. Line 14 says, _"if you happen to have *only* bash >= 4.1 installed, see further if not,"_ but that is the only mention of a specific bash version in that file. It is briefly mentioned in the [CONTRIBUTING.md](https://github.com/scop/bash-completion/blob/master/CONTRIBUTING.md) file, and also buried in the [CHANGES](https://github.com/scop/bash-completion/blob/master/CHANGES) file, but this is NOT a case of me lazily failing to read clear documentation. I had to dig through the Git commits, doing diffs between tags, before I finally [found it mentioned for v1.9.0](https://github.com/scop/bash-completion/commit/935ce88df7f6bfef86e44c732228f8575ca3cd67). Your snarky comment, sir, is neither justified, nor appreciated. 

Regardless, I have already withdrawn my proposal that we use bash-completion within our environment. I am not willing to go through the red tape of also packaging and distributing a newer version of bash along with bash-completion. If one of my colleagues wants to fight that battle, they're welcome to do so, but I will just use the [fish shell](https://fishshell.com/) or [zsh](http://www.zsh.org/).
