### ISSUE TITLE
Add completion for android tools

### ISSUE THREAD

**Issue by anatol** [scop/bash-completion#27]
Thanks for starting `adb` completion file.

I've been using this completion that worked very well for me https://github.com/mbrubeck/android-completion

I see that @mbrubeck completion covers more use-cases than the one in this repo. Is it possible that you look at mbrubeck`s code and pull more`adb` use-cases?

There is also `fastboot` completion. Could you please add or pull mbrubeck's `fastboot` completion?

**Comment by scop** [comment]
If @mbrubeck wants to submit his completions to bash-completion, and is willing to help maintaining them here, I can have a look. Even better would be if those completions were shipped with the actual android tools themselves, so try submitting them there first?

**Comment by mbrubeck** [comment]
Hi!  I'm not doing a very good job of maintaining those completions currently, since I don't do much Android development these days, though I have been reviewing and merging PRs that other people submit.  If anyone wants to find a new home for them and/or step up as maintainer, I'd be happy to help however I can.

**Comment by ubaierbhat** [comment]
Google actually provides a bash completion file as part of sdk.

https://android.googlesource.com/platform/sdk/+/refs/tags/android-vts-9.0_r6/bash_completion/adb.bash

**Comment by scop** [comment]
Ah, great, it's better to have this upstream alongside the shipped adb; I've deprecated the one in bash-completion.
