### ISSUE TITLE
Question: Is it OK to source a file from a bash completion script?

### ISSUE THREAD

**Issue by elboulangero** [scop/bash-completion#281]
Hello there,

I'm writing a bash completion script for two commands, quodlibet and operon. These two commands are shipped by [Quodlibet](https://github.com/quodlibet/quodlibet/pull/3128).

I need to share some functions and variables between both, so my first attempt was to write only one script `quodlibet` with completions for the two commands, and add a symlink `operon -> quodlibet`. This seems to be the common approach for this situation.

However, adding a symlink is not super convenient for me. QL is cross-platform app, and it also works on Windows with MSYS2 and that uses bash + bash-completion. Apparently symlinks don't work in this world.

So instead, I would like to provide 3 scripts for completion: `quodlibet`, `operon`, and `ql-common` (or similar) for the common code, that would be sourced by both `quodlibet` and `operon`. However I couldn't find any completion scripts that do that already, so I'm wondering if I'm doing it wrong? Is it a bad idea, is there some reasons against doing that?

Thanks!

**Comment by scop** [comment]
I'm assuming you're writing the scripts for inclusion in quodlibet, not bash-completion? Within bash-completion, we already rely heavily on symlinks so adding more is not a problem. Also, if you're depending on bash-completion, the symlink issue is kind of already brought upon the target system by us, so I'm not sure if it's a concern for your completions to use them as well.

Anyway, I don't think there's anything wrong with the common code approach, there just kind of isn't need for that within bash-completion. Just make sure your common code file's name doesn't conflict/coincide with possible actual commands. Preferably install it somewhere outside of the dirs where completions are loaded from.

Some other random thoughts of other approaches: the completion files probably aren't too big to be actually duplicated, i.e. copied instead of symlinked. Uglyish but should work. And if you're willing to rely on bash-competion, we have _xfunc which might be useful too (it's a way to invoke functions defined in other completion files), see the sources for examples of use.

**Comment by elboulangero** [comment]
> I'm assuming you're writing the scripts for inclusion in quodlibet, not bash-completion?

Yes indeed.

> Also, if you're depending on bash-completion

If I use `_init_completion` or `_filedir`, I depend on on `bash-completion` right? I didn't realize that at first.

A bonus question comes to mind: in the context of package distribution (ie. debian), a package that uses `bash-completion` helpers should depend (or at least recommend) the bash-completion package, right?

> Also, if you're depending on bash-completion, the symlink issue is kind of already brought upon the target system by us, so I'm not sure if it's a concern for your completions to use them as well.

Interesting, indeed. The developer of QL seemed to say that symlinks don't work on this "Windows MSYS2" platform. However there's bash and [bash-completion](https://github.com/Alexpux/MSYS2-packages/blob/master/bash-completion/PKGBUILD) available there.

Since I know nothing about this platform, I have no idea if symlinks are replaced by copies automatically by their package build system, or if they do have symlinks. Hmm, anyway.

> Some other random thoughts of other approaches: the completion files probably aren't too big to be actually duplicated, i.e. copied instead of symlinked. Uglyish but should work.

I might go this way in the end, it looks like a good enough trade-off.

**Comment by scop** [comment]
I don't know of Debian's policies for packages containing completions, but for Fedora it at least used to be the case that no hard dependencies should be added, and I don't think even Recommends was supposed to be there (at least if the completions are included with the "main" package content). I think the same would make sense for Debian, but I suggest checking from them direectly. Maybe @gftg85 knows?

**Comment by gftg85** [comment]
>A bonus question comes to mind: in the context of package distribution (ie. debian), a package that uses bash-completion helpers should depend (or at least recommend) the bash-completion package, right?

'Depends' is certainly incorrect, and it's my understanding that even 'Recommends' is wrong for bash-completion.  Debian has the 'Suggests' field, which should probably be used in this case.

Debian policy states ([reference](https://www.debian.org/doc/debian-policy/ch-relationships.html)):

- Recommends
 This declares a strong, but not absolute, dependency.
 The Recommends field should list packages that would be found together with this one in all but unusual installations.
- Suggests
 This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.

Interpreting the meaning of these fields is rather subjective, and I don't have an indisputable answer (as a matter of fact, similar issues have been raised at least once in the past, for instance in this [thread](https://lists.debian.org/debian-devel/2017/05/msg00370.html)).

As for current practice, if you have access to a Debian machine, you can use the following commands to list what packages suggest or recommend bash-completion:

```
apt-rdepends --reverse -s Suggests bash-completion
apt-rdepends --reverse -s Recommends bash-completion
```

Although both commands return hits, I'd say that using 'Suggests' is less controversial.

**Comment by elboulangero** [comment]
> Although both commands return hits, I'd say that using 'Suggests' is less controversial.

I agree, `Suggests` seems to be a better bet than `Recommends`, given the definition you just quoted above.

Thanks all for taking the time to share all the information here!

**Comment by scop** [comment]
I think conceptually spot on would be "suggested for interactive bash users", but it's not possible to specify something like that. Plain `Suggests: bash-completion` doesn't even take into account if bash is installed or not. And merely check for whether bash is installed wouldn't cut it, because it quite probably is just about everywhere, including on systems where no users use it as an interactive shell. So FWIW I'm personally somewhat torn between `Suggests: bash-completion` or leaving even that out entirely, and would probably just follow what most other packages do between those two choices.
