### ISSUE TITLE
completion for `date --iso-8601` missing the optional parameter

### ISSUE THREAD

**Issue by pabs3** [scop/bash-completion#328]
The completion in bash-completion 2.18 for the `date` command is missing the optional parameter to the `--iso-8601` option. Also when I type the = character and complete after it, I don't get completion for the possible values. I note the parameters to the `--rfc-3339` option are also not completed.

```
$ date --
--date        --date=       --debug       --help        --iso-8601    --reference=  --rfc-3339=   --rfc-email   --set=        --universal   --version     
$ date --iso-8601 
2019-06-19
$ date --iso-8601=
date: ambiguous argument ‘’ for ‘--iso-8601’
Valid arguments are:
  - ‘hours’
  - ‘minutes’
  - ‘date’
  - ‘seconds’
  - ‘ns’
Try 'date --help' for more information.
$ date --iso-8601=seconds
2019-06-19T13:54:45+08:00
$ date --help | grep -A4 -- --iso-8601
  -I[FMT], --iso-8601[=FMT]  output date/time in ISO 8601 format.
                               FMT='date' for date only (the default),
                               'hours', 'minutes', 'seconds', or 'ns'
                               for date and time to the indicated precision.
                               Example: 2006-08-14T02:34:56-06:00
$ date --version
date (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by scop** [comment]
(I suppose you mean bash-completion 2.8) Anyway, `date` is completed using a generic long option parser, so not offering the `--iso-8601` or `--rfc-3339` arguments is expected; it's not feasible to implement that kind of parsing in it. Also, I think just listing `--iso-8601` without the `=` is fine, because the argument is actually optional, and people knowing better can just insert the `=`. Showing both wouldn't be that helpful because as noted, we cannot assist with argument completions with the `=` anyway.

Closing because this in my opinion is as good as it's going to get with the generic parser, and I don't think we'll want to keep open issues to implement more dedicated to all completions that are currently using it, nor to single out `date` of those.

**Comment by pabs3** [comment]
I understand that you don't want to keep issues open for switching
everything from the generic long option parser but would it be possible
to switch date to using a different function than the generic one?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by scop** [comment]
Sure, but at the moment there is no such function.
