### ISSUE TITLE
Version 2.9 tarball contains `install-sh` and `missing` with broken shebangs

### ISSUE THREAD

**Issue by yumitsu** [scop/bash-completion#331]
Good day. Looks like 2.9 tarball contains `install-sh` and `missing` scripts with broken shebang:
```
#!/usr/bin/sh
# install - install a program, script, or datafile
```

It breaks installation on macOS and, I believe, on other systems with packet managers which use release tarball:
```
/bin/sh: .././install-sh: /usr/bin/sh: bad interpreter: No such file or directory
make[2]: *** [install-bashcompDATA] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
```

**Comment by scop** [comment]
Hm, the tarball is generated in CI in the Fedora development container, I suppose they have had a broken automake at the time the tarball was generated. I'll switch it to be done on Alpine, suppose that's more stable. The tarball is already out there though, I won't be replacing it, but hopefully future ones will not have this problem.

**Comment by yumitsu** [comment]
@scop Thanks a lot, but it still means a lot of users will stay without version 2.9 on macOS - I guess very few will build it from source

**Comment by scop** [comment]
That's unfortunate, but replacing a released tarball is not something I will do, because doing so would cause alerts for checksum checks elsewhere and people starting to spend time diggging through if something malicious has happened.

I should probably release more often than I have in the past. But in the meantime, I think it wouldn't be that big a deal for affected distro/package maintainers to temporarily fix the issue in their build recipes e.g. with a sed oneliner.
