### ISSUE TITLE
Error completing '.'

### ISSUE THREAD

**Issue by mcint** [scop/bash-completion#360]
Error when attempting completion for `.`: `-bash: .: syntax error: operand expected (error token is ".")`.

In `__load_completion ()` in the 2nd-from-last line, `[[ -n "${_xspecs[$cmd]}" ]] &&`, specifically `"${_xspecs[$cmd]}"` fails when `cmd` is `.`.

**Comment by mcint** [comment]
Eh, can be closed. Of the versions I can test against, it only affects `5.0.0(1)-release`. Fixed at or before `5.0.11(1)-release`.

**Comment by rduplain** [comment]
Posting to a closed issue in order to document the cause and workaround. The issue can stay closed, as it's not a bug in bash-completion as documented. It's also not a bash version issue other than requiring bash 4+ to support associative arrays.

The bash error message is the result of looking up `.` on a variable that isn't declared as an associative array:

```
$ echo "${doesnotexist[.]}"
bash: .: syntax error: operand expected (error token is ".")
```

This can happen if you source `bash_completion` dynamically during a completion. For example, a default completer that sources bash-completion then returns 124 to signal to bash that it should retry completion.

If `.` bash completion results in a syntax error, the workaround is to declare the associative array variable:

```bash
declare -A _xspecs
```

... before sourcing `bash_completion` at runtime during completion. Alternatively, you could add this `declare` to your bash init (profile/bashrc).

**Comment by scop** [comment]
See #210 and a47bd375bb0f95dc6d388d4097c420bddb72ae33

**Comment by rduplain** [comment]
Thanks for adding references! Looks good.
