### ISSUE TITLE
brew install bash-completion@2 not working

### ISSUE THREAD

**Issue by nicole-brewer** [scop/bash-completion#387]
Info:
MacOS Mojave 10.14.16
GNU bash, version 5.0.16
git version 2.25.0

So far I have...
 
`brew install git bash-completion@2`

I have sourced my .bash_profile which reads
'[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"`

`$ ls -l` 
`/usr/local/etc/profile.d/bash_completion.sh -> ../../Cellar/bash-completion@2/2.10/etc/profile.d/bash_completion.sh`

I've checked that `which git`  to verify that `/usr/local/bin/git -> usr/local/Cellar/git/2.25.0_1/bin/git`

I've checked that bash completions for git have been installed to '/usr/local/etc/bash_completion.d`

I'm stumped. Any ideas?

**Comment by scop** [comment]
Seems this is something specific to the brew bash-completion installation. I don't think they lurk around here, so I suggest contacting them directly about this.

Anyway, the generic troubleshooting instructions here could also help with the debugging, see Troubleshooting in README.md.

**Comment by nicole-brewer** [comment]
I don't believe this is a homebrew problem since I have checked that all the bash-completion files exist and are in the right place. Even if I directly source the script `/usr/local/etc/profile.d/bash_completion.sh. bash-completion doesn't work at all for me (or give me any debug info when i `set -v`). Do you have any other ideas?

**Comment by scop** [comment]
This is very likely an installation dependent issue, and since it's a brew installation...

Anyway, you can try a `set -x` in a shell, the source your `/usr/local/etc/profile.d/bash_completion.sh` there; that should give you some info where to start the hunt.

**Comment by richtong** [comment]
I have the same issue @nicole-brewer did you ever get it resolved. I have brew bash-completion@1 on one machine and this works. Even if you disable the master script and source the git bash completions it doesn't work. Argh!

**Comment by nicole-brewer** [comment]
@richtong no updates from me, good luck!

**Comment by richtong** [comment]
OK I've bisected the problem, it looks like at least from me, it is because `brew install hub` is installing a bash completion (whcih doesn't work by the way) but it overwrites the git completions. this is because hub is alphabetically less in the `/usr/local/etc/bash-completions.d` 

As an aside, the debug process was a little painful, but in the homebrew recommendations, https://docs.brew.sh/Shell-Completion it says as an alternative, that you should either look for that completion bash script or just source everyscript in `$(brew --prefix)/etc/bash-completions.d` when I did that it didn't work, but if i rename git-completion.bash as z-git-completion.bash then it worked, so just bisected the files until I discovered that it was `$(brew --prefix)/bash-completion/hub` that was the problem and hub <tab> doesn't work. 

Hub is the deprecated command line for github, they are moving to `gh` so a `brew uninstall hub` and it works. Wow really subtle bug!
