### ISSUE TITLE
_minimal is worse than the default bash completion (it doesn't auto complete wildcards)

### ISSUE THREAD

**Issue by averms** [scop/bash-completion#444]
Here `e` is an alias for my editor. Also, `build/` is a directory containing multiple pdf
files and bunch of other files. First, here is how it looks when the compspec is
`complete -F _minimal e`:
```sh
$ e bui<TAB>
```
which completes to `e build/`. So far, so good.
```sh
$ e build/*pdf<TAB>
```
This does not complete at all.

Now here is how it looks when `e` doesn't have a compspec:
```sh
$ e bui<TAB>
```
which completes to `e build/`.
```sh
$ e build/*pdf
```
This is where the bash default completion is better. This completes to `e build/my.pdf`.
I can press <kbd>TAB</kbd> again to go to the next pdf and so on.

Is it possible to either: (1) not generate a compspec at all for those commands and let
bash do its magic, or (2) have an option to do the above.
This is the cause of a lot of complaints on StackOverflow ([one], [two]).

[one]: https://unix.stackexchange.com/a/37723
[two]: https://unix.stackexchange.com/a/278449

**Comment by scop** [comment]
https://github.com/scop/bash-completion/blob/b12639a6becec13a0a2c06173ba40fb3bbe972e1/bash_completion#L2226

Not sure if that's still the case, test results welcome.

**Comment by a-vrma** [comment]
> Not sure if that's still the case, test results welcome.

It is. However, we can replace it with a `complete` command that is the same as the default behavior.
I've been running the following for about a week with satisfactory results:

```
--- /usr/share/bash-completion/bash_completion	2020-08-09 12:37:57.000000000 -0400
+++ bash_completion	2020-09-10 14:40:48.649789357 -0400
@@ -2224,7 +2224,7 @@
     __load_completion "$cmd" && return 124
 
     # Need to define *something*, otherwise there will be no completion at all.
-    complete -F _minimal -- "$cmd" && return 124
+    complete -o default -o bashdefault -- "$cmd" && return 124
 } &&
     complete -D -F _completion_loader
```

I'll also post the output of the tests soon.

**Comment by a-vrma** [comment]
Also, I asked on the Bash mailing list and the current maintainer said this:

> On 9/10/20 2:34 PM, Aman Verma wrote:
> > Hi, I was just wondering what would be a good way of emulating the
> > default compspec in Bash with an explicit `complete` command. 
> 
> complete -o bashdefault -o default
> 
> will get you pretty close.

**Comment by scop** [comment]
> Also, I asked on the Bash mailing list and the current maintainer said this:

Good to know.

Looking a bit into this, what replacing `_minimal` with the bash default would lose include
- improved array variable (index) completion
- improved completion for a few recognized variables (TZ=<kbd>Tab</kbd> etc, although it's either broken at the moment or I don't know how to invoke it, so not maybe not much of a loss)
- ...maybe nothing else

Until this can be more thoroughly figured out, it appears that an implementation close to your option (2) above would be to override the definition of `_minimal` with something like
```bash
_minimal() {
    [[ $2 == "$"* ]] || compopt -o filenames
    compopt -o bashdefault -o default
}
```
...after loading `bash_completion`.

**Comment by a-vrma** [comment]
That sounds like a good solution.

**Comment by ipaqmaster** [comment]
I've been dealing with this issue since I made bash-completion part of my SOE in Feb 2021, installing my distribution's `bash-completion` package and adding it in my /etc/bash.bashrc. I've dearly missed Bash's native glob completion and used to use it a lot before using bash-completion on my machines.

Since then I've tried to pinpoint the issue a few times and it took a while to realize it was bash-completion causing this behavior (Or sudden lack there of). I'd agree that it's a tedious problem to search for online given how many "sounds similar but not actually related at all" threads appear in the results. It got a lot easier to find relevant threads once I knew it was the result of using bash-completion and could include that in my search queries and check github.

All this time I was worried that it was the result of one specific completion under the /completions path (And how tedious that would be to `complete -r` one at a time until I find the culprit, but it turns out this issue is actually caused by complete tacking on _minimal to every command you hit <Tab> with automatically, preventing bash from doing its best.

In my own multiple attempts to figure out what was causing this I also learned that completion automatically tacks on `complete -F _minimal commandTabbedForGoesHere` for any command you've typed out then hit <TAB> in your prompt.

This also happens even if you hit <TAB> for a command which doesn't exist, bash-completion always tacks on _minimal even if you ctrl+c/backspace it the moment <TAB> were pressed a _minimal `complete` entry got created.

```
me@pc ~ $fakeCommand <TAB>^C
me@pc ~ $complete |grep fakeCommand
complete -F _minimal fakeCommand
me@pc ~ $
```

It would be nice if this `_minimal` feature could be worked around so all bash shell activity can rely on Bash's internal glob completion for when nothing else matches.

Bummer to see this has been open for so long without a fix but I'm glad the issue wasn't just closed and forgotten. I'm sure there's thousands of people with this issue but it's pretty niche to find relevant chatter online. Granted it's on me for not checking this github project's github issues sooner!

**Comment by scop** [comment]
I happened to think of this a bit recently. I'm toying with the idea of this patch to `_minimal`:
```diff
--- a/bash_completion
+++ b/bash_completion
@@ -2500,3 +2500,3 @@ _minimal()
     $split && return
-    _filedir
+    compopt -o bashdefault -o default
 }
```

This would preserve our improved array variable index completion, while falling back to the bash defaults for other goodness, including wildcard expansion. Thoughts? Ping @akinomyoga too.

**Comment by scop** [comment]
Also, if we find the above approach good, we might want to replace a plain `_filedir` with that in a lot of other places in the tree, too. Probably not everywhere, because in some places I suppose we want filename completions along with some others, and the above activates only as a fallback in case no others were generated.

**Comment by akinomyoga** [comment]
That seems to be a good solution.

Also, I think `$split && return` could also be removed from `_minimal`. The plain Bash shows the filenames for e.g. `my --file=*.sh[TAB]`, but bash-completion doesn't seem to produce the results even with the modification in https://github.com/scop/bash-completion/issues/444#issuecomment-1506495817.

**Comment by scop** [comment]
True that. https://github.com/scop/bash-completion/pull/928 has the fix.

**Comment by wanghaiqiangk** [comment]
@ipaqmaster This had me laughing right there. Isn't that exactly the situation I encountered? I had a compspec saved in a file outside the standard completion searching path. I always forgot to source it before attempting to hit TAB for completion. Then the _minimal hindered my completion from working properly,  and I had to reopen the terminal. Now that I know it's caused by _minimal, but previously, it was really frustrating to search here and there without good results.

**Comment by Geremia** [comment]
I get the issue where `ls *.html`+<kbd>TAB</kbd> works, but a command without defined bash-completions doesn't, e.g.: `firefox *.html`+<kbd>TAB</kbd>.

**Comment by akinomyoga** [comment]
> a command without defined bash-completions doesn't, e.g.: `firefox *.html`+TAB.

`firefix` isn't *a command without defined bash-completion*. The `firefox` completion supports filtering of the filenames at
https://github.com/scop/bash-completion/blob/5b171c6412c1020e5783270fe5e70bf4b7d60a1e/completions/firefox#L49, where globbing is not supported.

**Comment by Geremia** [comment]
@akinomyoga Good point. Thanks. 🙏 So to enable globbing, I'd have to do `__git_complete firefox __git_main `; but is there a one-liner to enable globbing on everything?
<hr>

Also, I have in my `~/.bashrc` an alias for `ls`:  `alias l="ls -ltaBhiN -I'.[a-zA-Z]*' --time-style=+'%F %H:%M:%S' --color"`. 
Why does `l *.html`+<kbd>TAB</kbd> work, but `ls *.html`+<kbd>TAB</kbd> doesn't show completions?

**Comment by akinomyoga** [comment]
>  is there a one-liner to enable globbing on everything?

No.

> Why does `l *.html`+TAB work, but `ls *.html`+TAB doesn't show completions?

Because the completions for `l` and `ls` are different.
