### ISSUE TITLE
OSTYPE check too strict in `watch`

### ISSUE THREAD

**Issue by celynwalters** [scop/bash-completion#453]
This is on the same lines as #122

I found that for [`watch`](https://github.com/scop/bash-completion/blob/master/completions/watch#L3) completions are not used on Mac OSX because of a check to the `OSTYPE` environment variable:

```bash
[[ $OSTYPE == *linux* ]] || return 1
```

Yes, `watch` isn't normally available on OSX, but it can be simply installed via `brew install watch`.
I couldn't find any others like this by doing a recursive `grep`.
Perhaps the line should be more like [`killall`](https://github.com/scop/bash-completion/blob/master/completions/killall#L3)?

```bash
[[ $OSTYPE == *@(linux|freebsd|darwin)* ]] || return 1
```

I don't know for which other OSes it can extend to, though.
On OSX my `OSTYPE` variable is `darwin18.7.0`.
I have this repo as a submodule in my dotfiles, so I'm always up to date with master.

**Comment by scop** [comment]
The point of exclusions like the current case at hand is not whether the command in question is usually available or not, but rather that the command by that name is usually something completely different than what the completion is written for. For example in the case of `watch`, compare https://linux.die.net/man/1/watch and https://www.unix.com/man-page/FreeBSD/8/watch/ -- so enabling this completion for watch on FreeBSD is not something we should do.

This is of course not a very good general pattern -- better would be to somehow detect whether the command we're completing is the expected one. There are some examples of this in the tree.

Now, I don't know what is the expected `watch` command on macs, but if you can confirm that there's no command called `watch` installed on macs by default, I think that alone would be enough to enable this completion for the `darwin`s.

Then again, perhaps we should look into some detection here instead. One possible (but still rather feeble) example would be to invoke `watch --help &>/dev/null` and if it doesn't indicate an error, install the completion, otherwise not. The `watch` on e.g. Ubuntu doesn't error out, but the FreeBSD does. How does yours behave?

**Comment by celynwalters** [comment]
Wow, what a detailed answer!

> The point of exclusions like the current case at hand is not whether the command in question is usually available or not, but rather that the command by that name is usually something completely different than what the completion is written for. For example in the case of `watch`, compare https://linux.die.net/man/1/watch and https://www.unix.com/man-page/FreeBSD/8/watch/ -- so enabling this completion for watch on FreeBSD is not something we should do.

Ah, I was just using it as an example. I don't know anything about FreeBSD.

> Now, I don't know what is the expected `watch` command on macs, but if you can confirm that there's no command called `watch` installed on macs by default, I think that alone + the info on brew installability would be enough to enable this completion for the `darwin`s.

I can confirm that there is no such existing command on Mac for `watch`. There are plenty of people online looking for alternative bash scripts to replace its functionality.
 
> Then again, perhaps we should look into some detection here instead. One possible (but still rather feeble) example would be to invoke `watch --help &>/dev/null` and if it doesn't indicate an error, install the completion, otherwise not. The `watch` on e.g. Ubuntu doesn't error out, but the FreeBSD does. How does yours behave?

Isn't this as good as checking if an executable with the same name exists on the path? The command wouldn't have to be run, and besides, checking the help page doesn't guarantee that it's the correct `watch` either (as opposed to say, a user-written python script which responds to --help properly)

**Comment by scop** [comment]
> I can confirm that there is no such existing command on Mac for `watch`.

Ok, 601b07c44710d544661a36cdf85afa2543b2a6b9 enables.

> Isn't this as good as checking if an executable with the same name exists on the path?

Arguably better, but as said, quite feeble. For example if it responds to `--help` with success, our help parser is likely to yield useful completions to `-`<kbd>Tab</kbd> even if isn't exactly what the completion is written for. And if it does _not_ respond to it with success, it almost certainly isn't as far as we currently know.

> The command wouldn't have to be run,

Invoking `--help` to detect would happen only once, so I don't think this is an issue.

> and besides, checking the help page doesn't guarantee that it's the correct `watch` either (as opposed to say, a user-written python script which responds to --help properly)

That's right, but see above.

I don't particularly insist on the detection at all. Now that the OSTYPE check has been relaxed to include macs, feel free to close this if you think that's enough.

**Comment by celynwalters** [comment]
Perfect, thanks a lot!
