### ISSUE TITLE
Unbound variable error for helm cli

### ISSUE THREAD

**Issue by pratik136** [scop/bash-completion#551]
## Describe the bug
Pressing <kbd>tab</kbd> when using the `helm` cli cancels the command with the message "BASH_COMP_DEBUG_FILE: unbound variable"

## To reproduce
1. Install the [helm cli](https://helm.sh/docs/intro/install/)
2. Type 'helm i <kbd>tab</kbd>'
3. See problem

## Expected behavior
Ideally we would expect the 'i' to expand to 'install'. Alternatively, the completion <kbd>tab</kbd> could simply be ignored.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Alpine Linux v3.14 running as a container
- [x] bash version, `echo "$BASH_VERSION"`: 5.1.4(1)-release
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11

## Debug trace
[bash-completions-error-debug-dump.txt](https://github.com/scop/bash-completion/files/6760468/bash-completions-error-debug-dump.txt)

**Comment by akinomyoga** [comment]
I cannot find any string `BASH_COMP_DEBUG_FILE` in the `bash-completion` repository. This is the issue in the completion scripts generated by `helm`. The completion script of `helm` seems to be generated by the command [`helm completion bash`](https://helm.sh/docs/helm/helm_completion_bash/#helm-completion-bash). The problematic completion code seems to be emitted by `GenBashCompletion` called at [cmd/helm/completion.go L132 (helm/helm)](https://github.com/helm/helm/blob/61e08c63374406f261c914e667092eb21c13c37b/cmd/helm/completion.go#L132). The function `GenBashCompletion` seems to be defined in a golang library, [spf13/cobra](https://github.com/spf13/cobra). The culprit is [bash_completions.go L27 (spf13/cobra)](https://github.com/spf13/cobra/blob/de187e874d1ca382320088f8f6d76333408e5c2e/bash_completions.go#L27-L29).

Since this is the problem of the completion script generator `spf13/cobra`, [there are so many affected scripts](https://github.com/search?q=BASH_COMP_DEBUG_FILE&type=code).

**Comment by scop** [comment]
Yeah, this is a long standing issue with cobra, and PR's such as https://github.com/spf13/cobra/pull/1321 have unfortunately been stuck waiting for a longish time. But I'm afraid there's nothing we can do about it here, a workaround is to turn `nounset` mode off.
