### ISSUE TITLE
linux apt-get install no candidate package，but apt-get remove working normal！ 

### ISSUE THREAD

**Issue by TLARP** [scop/bash-completion#62]
I install bash-completion by  apt-get install by apt-get install bash-completion,and then I set  source /etc/share/bash-completion/completion in ~/.bashrc ,apt-get inst + tab will become apt-get install ,but
when I type apt-get install mysql+tab ,no candidate package for example mysql-server ;I hava run apt-get   
update before!I am so depressed!can you give me some suggestion!

**Comment by scop** [comment]
First, you should not need to touch `~/.bashrc`, there's a snippet in `/etc/profile.d` that should be enabling bash-completion for you. Regarding the mysql+TAB completion issue, please check what `apt-cache --no-generate pkgnames mysql` outputs to see if there is something we could complete. If there are no problems there, see [general troubleshooting instructions](https://github.com/scop/bash-completion/blob/master/README.md).

**Comment by TLARP** [comment]
![default](https://cloud.githubusercontent.com/assets/8800579/17431780/454697ca-5b2e-11e6-8968-9ba8a434b014.PNG)
working normal!
![22222](https://cloud.githubusercontent.com/assets/8800579/17431921/e44d6d3a-5b2e-11e6-8d44-36de3b8ea5c8.PNG)
if I type apt-remove working ok,the candidate will show us,but I type apt-get install there nothing!so strange,I follow yours instructions things not changes!

**Comment by scop** [comment]
In your screenshots you're apparently trying to complete `apt-get install` but previously you said you're trying e.g. `apt-get install mysql`. Those are different things, and I assume the former might actually take some time because there will be lots of completions go generate/output.

The troubleshooting instructions contain information I need to see in order to be able to help. But chances are quite high that I cannot help even then, because I don't have easy access to a system with apt-get. I suggest asking from your distro forums/bug report system.

**Comment by TLARP** [comment]
Many Thanks！
