### ISSUE TITLE
Trying to complete the . builtin doesn't work

### ISSUE THREAD

**Issue by TestingPlant** [scop/bash-completion#703]
## Describe the bug

When trying to find completions for the `.` builtin command, the below messages appear:
```
bash_completion: /usr/share//bash-completion/completions/.: is a directory
bash_completion: /usr/share/bash-completion/completions/.: is a directory
```
These messages only appear when trying to find completions for `.` the first time.

## To reproduce

1. Run bash
2. Type `. `, including the trailing space
3. Press tab

## Expected behavior

Completions for the `.` builtin should appear

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: Arch Linux
- [x] bash version, `echo "$BASH_VERSION"`: 5.1.16(1)-release
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11.0

## Additional context

I'm using the `bash-completion-git` package from the AUR, which uses the latest code from the master branch. Using the normal `bash-completion` package which uses version 2.11 doesn't have this issue.

## Debug trace

[log.txt](https://github.com/scop/bash-completion/files/8114048/log.txt)

**Comment by abbeyj** [comment]
I bisected this down to ca361be02a92e30a3d26d376b30faf268853e836.  Possibly there should be a special case for `.`?  A similar problem also happens if trying to find completions for a command called `..` so if a special case is added for `.` then one for `..` would also be useful.  Alternatively maybe just going back to silently ignoring directories would be preferable?

**Comment by akinomyoga** [comment]
See #776
