### ISSUE TITLE
Bash completion triggers nss module

### ISSUE THREAD

**Issue by oxr463** [scop/bash-completion#820]
How does bash-completion interact with libnss? Double tapping tab in a terminal seems to trigger one of my nss modules but I don't see a completion in the repository named nss.

**Comment by scop** [comment]
Possibly not at all directly, possibly in a lot of ways under the hood when invoking commands to assist in generation of completions, not enough info here to say much more. The pre-filled issue template (that was apparently just erased here instead of filled) contains pointers and requests for info that might help with debugging and diagnosing. I suggest following them and filing a new issue report with them filled in case the obtained info points towards an issue in this project.

**Comment by oxr463** [comment]
I saw Bug and a Feature Request templates. This is more of a question, so I didn't think either applied. Thanks for the info!
