### ISSUE TITLE
Redirections require a space to work

### ISSUE THREAD

**Issue by scop** [scop/bash-completion#832]
## Describe the bug

Redirections require a space to work. i.e. to complete filenames.

## To reproduce

`cat <`<kbd>Tab</kbd> # gives no completion

`cat < `<kbd>Tab</kbd> # completes filenames as expected

Same thing with output redirections.

## Expected behavior

Redirections should complete files without having to enter a space after `>` or `<`.

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version:
- [ ] bash version, `echo "$BASH_VERSION"`:
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: current master

## Additional context

This is a regression introduced in commit 38150dbd

**Comment by akinomyoga** [comment]
Thanks for the information. Maybe I miss something, but couldn't we just revert the change? Here, `redir` appears to contain a glob pattern:

https://github.com/scop/bash-completion/blob/b545d7d8598562edefd6ee4319eb257ee3609409/bash_completion#L1362

I think it is expected to match as a glob pattern in `${cur##$redir}`, so SC2295 would be a false positive.

- [ShellCheck: SC2295 – Expansions inside `${..}` need to be quoted separately, otherwise they will match as a pattern.](https://www.shellcheck.net/wiki/SC2295)

**Comment by akinomyoga** [comment]
I created a PR at #1073.

**Comment by scop** [comment]
Yeah, I didn't dig too deep and was wondering if there was an actual reason to quote it. Thanks!
