### ISSUE TITLE
Over-eager positional param check in `_comp_compgen`

### ISSUE THREAD

**Issue by scop** [scop/bash-completion#958]
## Describe the bug

Trying to use a command containing string looking like a positional parameter reference with `_comp_compgen` but which isn't one runs at odds with the check in https://github.com/scop/bash-completion/blob/77c9fd69e1d6ffa285ab5f96970a5955ed281534/bash_completion#L524-L527

I don't think it's feasible to try and detect false positives like this one. Guess I'm suggesting we either remove the check, or standardize on a workaround.

## To reproduce

```bash
_comp_compgen -- -W '$(echo foo bar | awk "{ print \$2 }")'
```

## Expected behavior

No error.

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version:
- [ ] bash version, `echo "$BASH_VERSION"`:
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`:

**Comment by akinomyoga** [comment]
Actually, this is related to what I wanted to discuss finally. I have still many pending commits that I haven't submitted yet, and among them is 55facc3384f2daeeeb3214d7096dc7a8a0c355e3 related to this issue. 55facc3384f2daeeeb3214d7096dc7a8a0c355e3 is just a workaround, but I wanted to discuss how to deal with the typical `-W '$(...)'` cases.

There are three things to address.

- One is that as reported here `-W ''` has a limitation by its design. Although `awk '{print $1}'` is false-positive, a more frequent pattern `'$("$1" ... | ...)` does not work.
- There are also vulnerable cases of `-W "$(...)"` (notice that it is not single-quoted but double-quoted, where the problems can be caused when the output of command picks some strings containing `$(malicious code)` from somewhere (such as filenames).
- Another problem caused by `-W '$(...)'` is that it bypasses the check by shfmt and shellcheck. Actually, many of the fixes in #956 are revealed by converting `... -W '$(xxxx)'` to `stdout=$(xxx); ... -W '$stdout'`

All of these issues are caused by the behavior `-W` evaluating the shell expansions specified in the arguments. My current idea is to introduce a new `_comp_command split 'text'` that does not perform the expansions but just splits the arguments. Something like

```bash
_comp_compgen_split() {
    local -a input=("$@")
    local IFS=${_comp_compgen__ifs-$' \t\n'} # Note: let _comp_compgen define _ifs
    _comp_compgen -- -W '${input[*]}'
}
```
